jdi-testing/jdn

package.json
src/js/main.jsx
src/manifest.json
webpack.config.js

Add Antd framework

---

src/js/blocks/generate/left/GenerateBlock.jsx
src/js/blocks/generate/right/GeneralSettings.jsx
src/js/components/Checkbox/Checkbox.jsx
src/js/models/ConversionToCodeModel.jsx
src/js/models/GenerateBlockModel.jsx
src/js/models/RulesBlockModel.jsx
src/js/models/SettingsModel.jsx

Fixed auto download by clicking 'Generate' with enabled checkbox

Jdn 20/generate download checkbox

---

src/js/blocks/autoFind/AutoFind.jsx
src/js/blocks/autoFind/autoFindProvider/AutoFindProvider.jsx

Issue 115: 'Remove' button on 'Auto find' tab is available before/without results of Auto finding

---

src/js/blocks/generate/GeneralSettings.jsx
src/js/models/SettingsModel.jsx

Issue-100: Preferences:of 'Settings' tab aren't saved after jumping between tabs

---

package.json
src/js/blocks/autoFind/autoFindProvider/AutoFindProvider.jsx
src/js/blocks/autoFind/autoFindProvider/highlight.js
src/js/blocks/autoFind/autoFindProvider/pageData.js
src/js/blocks/autoFind/autoFindProvider/pageDataHandlers.js
src/manifest.json

Rework highlight processing

---

src/css/main.less
src/js/blocks/generate/GenerateBlock.jsx
src/js/models/GenerateBlockModel.jsx

Issue-112: Redesign checkboxes on URLs list

---

package.json
src/js/blocks/autoFind/autoFindProvider/AutoFindProvider.jsx
src/js/blocks/autoFind/autoFindProvider/highlight.js
src/js/blocks/autoFind/autoFindProvider/pageDataHandlers.js
src/js/blocks/autoFind/autoFindProvider/pageObject.js
src/manifest.json

remove elements from generation

---

src/js/blocks/autoFind/autoFindProvider/AutoFindProvider.jsx
src/js/blocks/autoFind/autoFindProvider/contentScripts/highlight.js
src/js/blocks/autoFind/autoFindProvider/highlight.js
src/js/blocks/autoFind/autoFindProvider/pageData.js
src/js/blocks/autoFind/autoFindProvider/pageDataHandlers.js
src/js/blocks/autoFind/autoFindProvider/pageObject.js

add xpath generation

---

src/js/blocks/autoFind/autoFindProvider/pageObject.js
src/js/main.jsx

Issue-158: Auto Find tab is first, # before ID tag name

---

package.json
src/js/blocks/autoFind/autoFindProvider/contentScripts/generationData.js
src/js/blocks/autoFind/autoFindProvider/pageObject.js
src/manifest.json

Issue-176: Correct generation of 'id' locator

---

src/js/blocks/autoFind/autoFindProvider/contentScripts/generationData.js

Issue-176: Added a new rules for naming id attribute

---

package.json
src/js/models/GenerateBlockModel.jsx
src/manifest.json

Issue-171: Incorrect autogenerated name by class name tag

---

manifest.json
package.json
src/js/blocks/autoFind/AutoFind.jsx
src/js/blocks/autoFind/autoFindProvider/AutoFindProvider.jsx
src/js/blocks/autoFind/autoFindProvider/contentScripts/reportProblemPopup/reportProblemPopup.js

Issue-205: Fixed error

---

manifest.json
package.json
src/js/blocks/autoFind/autoFindProvider/AutoFindProvider.jsx
src/js/blocks/autoFind/autoFindProvider/contentScripts/reportProblemPopup/reportProblemPopup.js
src/js/blocks/autoFind/autoFindProvider/contentScripts/saveJson.js

Issue-262: Taking a screenshot and saving a file at the same time

---

manifest.json
package.json
src/js/blocks/autoFind/autoFindProvider/contentScripts/reportProblemPopup/reportProblemPopup.js

Issue-267: Fixed issue with saving JSON during report a problem

---

manifest.json
package.json
src/js/blocks/autoFind/autoFindProvider/AutoFindProvider.jsx
src/js/blocks/autoFind/autoFindProvider/connector.js
src/js/blocks/autoFind/autoFindProvider/contentScripts/contextMenu/contextmenu.js
src/js/blocks/autoFind/autoFindProvider/contentScripts/highlight.css
src/js/blocks/autoFind/autoFindProvider/contentScripts/highlight.js

Issue-208: Change name feature

---

manifest.json
package.json
src/js/blocks/autoFind/autoFindProvider/contentScripts/reportProblemPopup/reportProblemPopup.js

Issue-269: Screenshot 'report problem' contains modal window

---

manifest.json
package.json
src/js/blocks/autoFind/autoFindProvider/contentScripts/reportProblemPopup/reportProblemPopup.js

Issue-274: Reporting problem email - 'Body' word

---

manifest.json
package.json
src/js/blocks/autoFind/utils/pageDataHandlers.js

/predict old endpoint was changed to new /mui-predict.

Feature: Endpoint was changed to new backend data.

---

manifest.json
package.json
src/js/blocks/autoFind/contentScripts/highlight.css
src/js/blocks/autoFind/contentScripts/highlight.js

Changes:
Tooltip is added
Label text is changed.

Протестировать отображение имени #281
